import os
import sys
import logging
import uuid

# ANSI escape codes for coloring output
GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
BLUE = "\033[94m"
RESET = "\033[0m"

# Setup Logger
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger("Phase2Verifier")

def log_success(msg: str):
    logger.info(f"{GREEN}[SUCCESS] {msg}{RESET}")

def log_error(msg: str):
    logger.error(f"{RED}[ERROR] {msg}{RESET}")

def log_warning(msg: str):
    logger.warning(f"{YELLOW}[WARNING] {msg}{RESET}")

def log_info(msg: str):
    logger.info(f"{BLUE}[INFO] {msg}{RESET}")

def verify_environment():
    log_info("Ensuring env is loaded...")
    from dotenv import load_dotenv
    load_dotenv()
    log_success("Environment successfully configured.")

def run_verification():
    log_info("=== SMART DOCUMENT ASSISTANT: PHASE 2 VERIFICATION RUN ===")

    # 1. Generate fictional policy file
    filename = "fictional_policy_verification.txt"
    file_path = os.path.abspath(filename)
    
    policy_content = (
        "Acme Corp Remote Work Policy Guidelines:\n"
        "All employees operating under remote arrangements are required to adhere to core working hours "
        "defined as 10:00 AM to 4:00 PM EST. Team members must ensure they are accessible on Slack and "
        "via email during this timeframe. Daily timesheets must be updated and submitted through the "
        "internal employee portal by Friday at 5:00 PM local time.\n\n"
        
        "Acme Corp Corporate Travel and Reimbursement Rules:\n"
        "Business trips must be pre-approved by direct managers. For flights under 4 hours, economy class "
        "booking is mandatory. Corporate meals are eligible for reimbursement up to a maximum limit of "
        "$75 per day. Itemized receipts for all transactions exceeding $25 must be uploaded to the travel "
        "dashboard within 30 calendar days following the conclusion of the trip.\n\n"
        
        "Acme Corp Hardware Procurement Policy:\n"
        "Full-time staff members are eligible for standard hardware upgrades including workstation laptops "
        "once every 3 years. Requests should be lodged via the IT ticketing system at least 15 days "
        "prior to the eligibility date. Accidental damage protection is covered by corporate insurance."
    )
    
    try:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(policy_content)
        log_success(f"Fictional policy file written: {file_path}")
    except Exception as e:
        log_error(f"Failed to write verification file: {e}")
        sys.exit(1)

    # 2. Ingest document & chunk
    try:
        from app.services.document_processor import ingest_document
        
        log_info("Passing file through document processor (ingestion, SQLite saving, and chunking)...")
        db_id, chunks = ingest_document(file_path, filename)
        
        log_success("Document successfully processed and chunked.")
        log_info(f"Generated SQLite Document ID: {db_id}")
        log_info(f"Number of generated text chunks: {len(chunks)}")
        
        assert db_id is not None, "SQLite document ID must not be None."
        assert len(chunks) > 0, "No chunks generated by document processor."
        
        # Verify metadata attachments
        for idx, chunk in enumerate(chunks):
            assert chunk.metadata["source"] == filename, "Chunk metadata 'source' filename is incorrect."
            assert chunk.metadata["document_id"] == db_id, "Chunk metadata 'document_id' does not match relational DB ID."
            assert chunk.metadata["chunk_index"] == idx, "Chunk metadata 'chunk_index' annotation is incorrect."
        log_success("Chunk metadata verification assertions passed.")
        
    except Exception as e:
        log_error(f"Document ingestion / chunking phase failed: {e}")
        # Clean up files before exiting
        if os.path.exists(file_path):
            os.remove(file_path)
        sys.exit(1)

    # 3. Add chunks to ChromaDB
    try:
        from app.services.vector_store import ingest_chunks, retrieve_documents, clear_vector_store
        
        log_info("Passing chunks to vector store to embed and save to ChromaDB...")
        chunk_ids = ingest_chunks(chunks)
        log_success(f"Ingested {len(chunk_ids)} chunks into ChromaDB.")
        assert len(chunk_ids) == len(chunks), "Chroma DB ingestion list size mismatch."
        
    except Exception as e:
        log_error(f"ChromaDB ingestion failed: {e}")
        cleanup(db_id, file_path)
        sys.exit(1)

    # 4. Perform Retrieval Search and assert correctness
    try:
        query = "What is the daily reimbursement limit for meals during corporate travel?"
        log_info(f"Executing semantic retrieval search for query: '{query}'")
        
        retrieved_docs = retrieve_documents(query, top_k=2)
        log_info(f"Retrieved {len(retrieved_docs)} chunks from Vector Store.")
        assert len(retrieved_docs) > 0, "Vector store returned empty search results."
        
        # Verify retrieved content contains answer
        found_reimbursement_info = False
        for doc in retrieved_docs:
            log_info(f"Retrieved Chunk Metadata: {doc.metadata}")
            log_info(f"Retrieved Chunk Content Preview: {doc.page_content[:150]}...")
            
            # Check for source, page and document_id in citation metadata
            assert "source" in doc.metadata, "Citation metadata 'source' is missing."
            assert doc.metadata["source"] == filename, "Citation source filename mismatch."
            assert "document_id" in doc.metadata, "Citation metadata 'document_id' is missing."
            assert doc.metadata["document_id"] == db_id, "Citation document ID mismatch."
            assert "page" in doc.metadata, "Citation metadata 'page' is missing."
            
            if "$75" in doc.page_content:
                found_reimbursement_info = True
                
        assert found_reimbursement_info, "Search query failed to retrieve the chunk containing meal reimbursement limit ($75)."
        log_success("Semantic retrieval search returned the correct answer and correct citation metadata.")
        
    except Exception as e:
        log_error(f"Semantic retrieval search test failed: {e}")
        cleanup(db_id, file_path)
        sys.exit(1)

    # 5. Clean up everything
    cleanup(db_id, file_path)
    log_success("All Phase 2 integration verifications completed successfully!")
    sys.exit(0)

def clean_sqlite_record(db_id: str):
    try:
        from app.database.config import SessionLocal
        from app.database.models import Document as DbDocument
        
        db = SessionLocal()
        try:
            db_doc = db.query(DbDocument).filter(DbDocument.id == db_id).first()
            if db_doc:
                db.delete(db_doc)
                db.commit()
                log_info(f"SQLite document record deleted: {db_id}")
        finally:
            db.close()
    except Exception as e:
        log_warning(f"Failed to delete SQLite document record {db_id}: {e}")

def cleanup(db_id: str, file_path: str):
    log_info("Cleaning up verification test artifacts...")
    # Delete temporary text file
    if os.path.exists(file_path):
        os.remove(file_path)
        log_info("Temporary policy file removed.")
        
    # Delete SQLite metadata record
    clean_sqlite_record(db_id)
    
    # Clear ChromaDB vector collection
    try:
        from app.services.vector_store import clear_vector_store
        clear_vector_store()
        log_info("ChromaDB vector store cleared.")
    except Exception as e:
        log_warning(f"Failed to clear ChromaDB vector store: {e}")

if __name__ == "__main__":
    verify_environment()
    run_verification()
